"""Guessed Home Assistant controls for documented OpenData write points."""

from datetime import time

from .definitions import SetUserCapability

SET_USER_CAPABILITIES: tuple[SetUserCapability, ...] = (
    SetUserCapability(
        11009,
        "existing_control_transport",
        "Direct AC charging limit write; keep the existing user control unchanged",
    ),
    SetUserCapability(
        2618,
        "existing_control_transport",
        "Direct grid-charging write; keep the existing user control unchanged",
    ),
    SetUserCapability(
        6505,
        "existing_control_transport",
        "Direct backup-SOC write; keep the existing user control unchanged",
    ),
    SetUserCapability(
        11010,
        "existing_control_transport",
        "Direct feed-in-limit write; keep the existing user control unchanged",
    ),
    SetUserCapability(
        15203,
        "external_data_injection",
        "Meter phase-U power injection",
    ),
    SetUserCapability(
        15204,
        "external_data_injection",
        "Meter phase-U companion-value injection",
    ),
    SetUserCapability(
        18000,
        "external_data_injection",
        "Smart-socket state injection",
    ),
    SetUserCapability(
        18001,
        "external_data_injection",
        "Smart-socket power injection",
    ),
    SetUserCapability(
        35001,
        "time",
        "Deep Sleep Start Time",
        key="deep_sleep_start_time",
        user_value=time(18, 30),
        wire_value=0x121E,
        read_point=35001,
        expected_initial_state="18:30:00",
    ),
    SetUserCapability(
        35002,
        "time",
        "Deep Sleep End Time",
        key="deep_sleep_end_time",
        user_value=time(6, 30),
        wire_value=0x061E,
        read_point=35002,
        expected_initial_state="06:30:00",
    ),
    SetUserCapability(
        35005,
        "select",
        "LED Light-strip Mode",
        key="led_light_strip_mode",
        user_value="On",
        wire_value=1,
        read_point=7171,
        expected_initial_state="On",
        options=("Off", "On", "Low-power"),
    ),
    SetUserCapability(
        8646,
        "number",
        "Forced Full-charge Interval",
        key="forced_full_charge_interval",
        user_value=30.0,
        wire_value=30.0,
        read_point=8646,
        expected_initial_state="30",
        minimum=0,
        maximum=60,
        step=1,
        unit="d",
    ),
    SetUserCapability(
        8647,
        "time",
        "Forced Full-charge Start Time",
        key="forced_full_charge_start_time",
        user_value=time(8, 0),
        wire_value=0x0800,
        read_point=8647,
        expected_initial_state="08:00:00",
    ),
    SetUserCapability(
        2802,
        "number",
        "Forced AC Charging Power",
        key="forced_ac_charging_power",
        user_value=100.0,
        wire_value=100.0,
        read_point=2802,
        expected_initial_state="100",
        minimum=100,
        maximum=2400,
        step=1,
        unit="W",
    ),
    SetUserCapability(
        4,
        "existing_select_extension",
        "Work Mode",
        key="work_mode",
        user_value="Custom Time Control Mode",
        wire_value=6,
        read_point=7101,
        expected_initial_state="Self-Consumed Prioritized",
        options=(
            "Self-Consumed Prioritized",
            "Real-Time Control",
            "Charge/Discharge Schedule",
            "Custom Time Control Mode",
        ),
    ),
    *(
        SetUserCapability(
            point=12197 + slot,
            exposure="number",
            key=f"simulated_load_slot_{slot + 1:02d}",
            name=f"Simulated Load Time Slot {slot + 1}",
            user_value=float(100 + slot),
            wire_value=float(100 + slot),
            read_point=26000 + slot,
            expected_initial_state=str(100 + slot),
            enabled_by_default=False,
            minimum=0,
            maximum=10800,
            step=1,
            unit="W",
        )
        for slot in range(48)
    ),
)
