"""Home Assistant controls for documented OpenData write points."""

from __future__ import annotations

from datetime import time

from homeassistant.components.number import NumberDeviceClass, NumberMode
from homeassistant.const import EntityCategory

from .definitions import SetUserCapability

UINT16_MAX = 0xFFFF

SET_USER_CAPABILITIES: tuple[SetUserCapability, ...] = (
    SetUserCapability(
        11009,
        "existing_control_transport",
        "Documented direct AC charging point; keep the 1.2 read-11009/write-1138 "
        "control unchanged",
    ),
    SetUserCapability(
        2618,
        "existing_control_transport",
        "Documented direct grid-charging point; keep the 1.2 read-2618/write-1143 "
        "control unchanged",
    ),
    SetUserCapability(
        6505,
        "existing_control_transport",
        "Documented direct backup-SOC point; keep the 1.2 read-6105/write-1142 "
        "control unchanged",
    ),
    SetUserCapability(
        11010,
        "existing_control_transport",
        "Direct feed-in-limit write; keep the existing user control unchanged",
    ),
    SetUserCapability(
        15203,
        "external_data_injection",
        "Meter phase-U power injection",
    ),
    SetUserCapability(
        15204,
        "external_data_injection",
        "Meter phase-U companion-value injection",
    ),
    SetUserCapability(
        18000,
        "external_data_injection",
        "Smart-socket state injection",
    ),
    SetUserCapability(
        18001,
        "external_data_injection",
        "Smart-socket power injection",
    ),
    SetUserCapability(
        35001,
        "time",
        "Deep Sleep Start Time",
        translation_key="deep_sleep_start_time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:clock-start",
        key="deep_sleep_start_time",
        user_value=time(18, 30),
        wire_value=0x121E,
        read_point=35001,
        read_sample_value=0x121E,
        expected_initial_state="18:30:00",
    ),
    SetUserCapability(
        35002,
        "time",
        "Deep Sleep End Time",
        translation_key="deep_sleep_end_time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:clock-end",
        key="deep_sleep_end_time",
        user_value=time(6, 30),
        wire_value=0x061E,
        read_point=35002,
        read_sample_value=0x061E,
        expected_initial_state="06:30:00",
    ),
    SetUserCapability(
        35005,
        "select",
        "LED Light-strip Mode",
        translation_key="led_light_strip_mode",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:led-strip-variant",
        key="led_light_strip_mode",
        user_value="on",
        wire_value=1,
        read_point=7171,
        read_sample_value=1,
        expected_initial_state="on",
        options=("off", "on", "low_power"),
    ),
    SetUserCapability(
        8646,
        "number",
        "Forced Full-charge Interval",
        translation_key="forced_full_charge_interval",
        device_class=NumberDeviceClass.DURATION,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        key="forced_full_charge_interval",
        user_value=30.0,
        wire_value=30,
        integer_wire_value=True,
        read_point=8646,
        read_sample_value=30,
        expected_initial_state="30",
        minimum=0,
        maximum=60,
        step=1,
        unit="d",
    ),
    SetUserCapability(
        8647,
        "time",
        "Forced Full-charge Start Time",
        translation_key="forced_full_charge_start_time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:clock-start",
        key="forced_full_charge_start_time",
        user_value=time(8, 0),
        wire_value=0x0800,
        read_point=8647,
        read_sample_value=0x0800,
        expected_initial_state="08:00:00",
    ),
    SetUserCapability(
        2802,
        "number",
        "Forced AC Charging Power",
        translation_key="forced_ac_charging_power",
        device_class=NumberDeviceClass.POWER,
        entity_category=EntityCategory.CONFIG,
        mode=NumberMode.BOX,
        key="forced_ac_charging_power",
        user_value=100.0,
        wire_value=100,
        integer_wire_value=True,
        read_point=2802,
        read_sample_value=100,
        expected_initial_state="100",
        minimum=100,
        maximum=2400,
        step=1,
        unit="W",
    ),
    SetUserCapability(
        4,
        "existing_select_extension",
        "Work Mode",
        translation_key="work_mode",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:cog",
        key="work_mode",
        user_value="Custom Time Control Mode",
        wire_value=6,
        read_point=7101,
        read_sample_value=1,
        expected_initial_state="Self-Consumed Prioritized",
        options=(
            "Self-Consumed Prioritized",
            "Real-Time Control",
            "Charge/Discharge Schedule",
            "Custom Time Control Mode",
        ),
        create_requires_read_value=False,
    ),
    *(
        SetUserCapability(
            point=12197 + slot,
            exposure="number",
            key=f"simulated_load_slot_{slot + 1:02d}",
            name=f"Simulated Load Time Slot {slot + 1}",
            translation_key="simulated_load_time_slot",
            translation_placeholders={"slot": str(slot + 1)},
            device_class=NumberDeviceClass.POWER,
            entity_category=EntityCategory.CONFIG,
            mode=NumberMode.BOX,
            icon="mdi:transmission-tower-import",
            user_value=float(100 + slot),
            wire_value=100 + slot,
            integer_wire_value=True,
            read_point=26000 + slot,
            read_sample_value=100 + slot,
            expected_initial_state=str(100 + slot),
            enabled_by_default=False,
            minimum=0,
            maximum=UINT16_MAX,
            step=1,
            unit="W",
        )
        for slot in range(48)
    ),
)
