from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.const import (
    PERCENTAGE,
    EntityCategory,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfTemperature,
)

from .entity_description import (
    IndevoltSensorEntityDescription,
    format_firmware_version,
)

BATTERY_PACK1_SENSORS = {
    IndevoltSensorEntityDescription(
        key="1136",
        translation_key="battery_pack_1_firmware_dcdc",
        name="Firmware SFA/PFA DCDC1",
        entity_category=EntityCategory.DIAGNOSTIC,
        value_fn=lambda value: format_firmware_version(version=value),
    ),
    IndevoltSensorEntityDescription(
        key="1137",
        translation_key="battery_pack_1_firmware_bms",
        name="Firmware SFA/PFA BMS1",
        entity_category=EntityCategory.DIAGNOSTIC,
        value_fn=lambda value: format_firmware_version(version=value),
    ),
    IndevoltSensorEntityDescription(
        key="9016",
        translation_key="battery_pack_1_soc",
        name="Battery SOC-Pack1",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="9020",
        translation_key="battery_pack_1_voltage",
        name="Battery V-Pack1",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="19173",
        translation_key="battery_pack_1_current",
        name="Battery I-Pack1",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="9030",
        translation_key="battery_pack_1_temperature",
        name="Battery Temp-Pack1",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="9021",
        translation_key="battery_pack_1_cell_1_voltage",
        name="Battery Cell1 V-Pack1",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="9023",
        translation_key="battery_pack_1_cell_2_voltage",
        name="Battery Cell2 V-Pack1",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
}

BATTERY_PACK2_SENSORS = {
    IndevoltSensorEntityDescription(
        key="1138",
        translation_key="battery_pack_2_firmware_dcdc",
        name="Firmware SFA/PFA DCDC2",
        entity_category=EntityCategory.DIAGNOSTIC,
        value_fn=lambda value: format_firmware_version(version=value),
    ),
    IndevoltSensorEntityDescription(
        key="1139",
        translation_key="battery_pack_2_firmware_bms",
        name="Firmware SFA/PFA BMS2",
        entity_category=EntityCategory.DIAGNOSTIC,
        value_fn=lambda value: format_firmware_version(version=value),
    ),
    IndevoltSensorEntityDescription(
        key="9035",
        translation_key="battery_pack_2_soc",
        name="Battery SOC-Pack2",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="9039",
        translation_key="battery_pack_2_voltage",
        name="Battery V-Pack2",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="19174",
        translation_key="battery_pack_2_current",
        name="Battery I-Pack2",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="9049",
        translation_key="battery_pack_2_temperature",
        name="Battery Temp-Pack2",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="9040",
        translation_key="battery_pack_2_cell_1_voltage",
        name="Battery Cell1 V-Pack2",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="9042",
        translation_key="battery_pack_2_cell_2_voltage",
        name="Battery Cell2 V-Pack2",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
}

BATTERY_PACK3_SENSORS = {
    IndevoltSensorEntityDescription(
        key="1140",
        translation_key="battery_pack_3_firmware_dcdc",
        name="Firmware SFA/PFA DCDC3",
        entity_category=EntityCategory.DIAGNOSTIC,
        value_fn=lambda value: format_firmware_version(version=value),
    ),
    IndevoltSensorEntityDescription(
        key="1141",
        translation_key="battery_pack_3_firmware_bms",
        name="Firmware SFA/PFA BMS3",
        entity_category=EntityCategory.DIAGNOSTIC,
        value_fn=lambda value: format_firmware_version(version=value),
    ),
    IndevoltSensorEntityDescription(
        key="9054",
        translation_key="battery_pack_3_soc",
        name="Battery SOC-Pack3",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="9058",
        translation_key="battery_pack_3_voltage",
        name="Battery V-Pack3",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="19175",
        translation_key="battery_pack_3_current",
        name="Battery I-Pack3",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="9068",
        translation_key="battery_pack_3_temperature",
        name="Battery Temp-Pack3",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="9059",
        translation_key="battery_pack_3_cell_1_voltage",
        name="Battery Cell1 V-Pack3",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="9061",
        translation_key="battery_pack_3_cell_2_voltage",
        name="Battery Cell2 V-Pack3",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
}

BATTERY_PACK4_SENSORS = {
    IndevoltSensorEntityDescription(
        key="1142",
        translation_key="battery_pack_4_firmware_dcdc",
        name="Firmware SFA/PFA DCDC4",
        entity_category=EntityCategory.DIAGNOSTIC,
        value_fn=lambda value: format_firmware_version(version=value),
    ),
    IndevoltSensorEntityDescription(
        key="1143",
        translation_key="battery_pack_4_firmware_bms",
        name="Firmware SFA/PFA BMS4",
        entity_category=EntityCategory.DIAGNOSTIC,
        value_fn=lambda value: format_firmware_version(version=value),
    ),
    IndevoltSensorEntityDescription(
        key="9149",
        translation_key="battery_pack_4_soc",
        name="Battery SOC-Pack4",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="9153",
        translation_key="battery_pack_4_voltage",
        name="Battery V-Pack4",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="19176",
        translation_key="battery_pack_4_current",
        name="Battery I-Pack4",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="9163",
        translation_key="battery_pack_4_temperature",
        name="Battery Temp-Pack4",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="9154",
        translation_key="battery_pack_4_cell_1_voltage",
        name="Battery Cell1 V-Pack4",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="9156",
        translation_key="battery_pack_4_cell_2_voltage",
        name="Battery Cell2 V-Pack4",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
}

BATTERY_PACK5_SENSORS = {
    IndevoltSensorEntityDescription(
        key="1098",
        translation_key="battery_pack_5_firmware_dcdc",
        name="Firmware SFA/PFA DCDC5",
        entity_category=EntityCategory.DIAGNOSTIC,
        value_fn=lambda value: format_firmware_version(version=value),
    ),
    IndevoltSensorEntityDescription(
        key="1099",
        translation_key="battery_pack_5_firmware_bms",
        name="Firmware SFA/PFA BMS5",
        entity_category=EntityCategory.DIAGNOSTIC,
        value_fn=lambda value: format_firmware_version(version=value),
    ),
    IndevoltSensorEntityDescription(
        key="9202",
        translation_key="battery_pack_5_soc",
        name="Battery SOC-Pack5",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="9206",
        translation_key="battery_pack_5_voltage",
        name="Battery V-Pack5",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="19177",
        translation_key="battery_pack_5_current",
        name="Battery I-Pack5",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="9216",
        translation_key="battery_pack_5_temperature",
        name="Battery Temp-Pack5",
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="9219",
        translation_key="battery_pack_5_cell_1_voltage",
        name="Battery Cell1 V-Pack5",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    IndevoltSensorEntityDescription(
        key="9222",
        translation_key="battery_pack_5_cell_2_voltage",
        name="Battery Cell2 V-Pack5",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
}

BATTERY_PACK_SENSORS = {
    1: BATTERY_PACK1_SENSORS,
    2: BATTERY_PACK2_SENSORS,
    3: BATTERY_PACK3_SENSORS,
    4: BATTERY_PACK4_SENSORS,
    5: BATTERY_PACK5_SENSORS,
}
